enc_id = '00AcsJnQWm+0tEzLoxDW6pGo0aFVGzA7X9bgmsjECD3bF9w34+EAHhbAu9VJpkbBYzK6s='
password = '01AQ9OPNqWKV/mWPJCmahFA99Wgz9VZlGp7Fk8CZYhbl1gFCQLw7RR/zy5I+NHKgWvcT8npD4qHioPBq2UG+RUTSHDrnAn3ESWsqCtClHScR8mRmeC9YGL'
salt = 'zi8gtrwsnwqakmmppirm68upkm9habr8'
key_pair = [
    [
    166,
    176,
    41,
    173,
    46,
    89,
    170,
    163,
    159,
    205,
    147,
    15,
    140,
    122,
    205,
    158,
    205,
    169,
    255,
    112,
    79,
    125,
    61,
    150,
    190,
    213,
    120,
    148,
    239,
    171,
    62,
    6,
    43,
    67,
    169,
    214,
    49,
    119,
    189,
    142,
    30,
    212,
    169,
    53,
    173,
    4,
    47,
    137,
    71,
    189,
    197,
    48,
    182,
    153,
    116,
    244,
    46,
    229,
    195,
    71,
    1,
    144,
    199,
    150,
],
    [
    43,
    67,
    169,
    214,
    49,
    119,
    189,
    142,
    30,
    212,
    169,
    53,
    173,
    4,
    47,
    137,
    71,
    189,
    197,
    48,
    182,
    153,
    116,
    244,
    46,
    229,
    195,
    71,
    1,
    144,
    199,
    150,
],
]
key_confirmed = true

[keys_confirmed]
rd = true
rs-ny = true
