remote_id = '360619722'
kb_layout_type = ''
size = [
    0,
    0,
    0,
    0,
]
fav = ['360619722']

[options]
remote-menubar-drag-left = '0.0'
remote-menubar-drag-right = '1.0'

[ui_flutter]
peer-tab-index = '2'
wm_Main = '{"width":800.0,"height":600.0,"offsetWidth":0.0,"offsetHeight":0.0,"isMaximized":true,"isFullscreen":false}'
peer-sorting = 'Remote ID'
wm_RemoteDesktop = '{"width":1300.0,"height":728.0,"offsetWidth":43.0,"offsetHeight":0.0,"isMaximized":false,"isFullscreen":true}'
